const encounterData = {
    "routes": {
        "Starter": { "gift": ["Bulbasaur", "Squirtle", "Charmander", "Chikorita", "Totodidle", "Cyndaquil", "Treeko", "Mudkip", "Torchic", "Turtwig", "Piplup", "Chimchar", "Snivy", "Oshawott", "Tepig", "Chespin", "Froakie", "Fennekin", "Rowlet", "{Popplio", "Litten", "Grookey", "Sobble", "Scorbunny", "Sprigatito", "Quaxly", "Fuecoco"] },
        "Route 101": { "grass": [] },
        "Route 102": { "grass": [], "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 103": { "grass": [], "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 104": { "grass": [], "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Petalburg Woods": { "grass": [] },
        "Rusturf Tunnel": { "grass": [] },
        "Dewford Town": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Granite Cave": { "grass": [], "surf": [] },
        "Route 105": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 106": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 107": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 108": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Abandoned Ship": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 109": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Slateport City": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 110": { "grass": [] },
        "New Mauville": { "grass": [] },
        "Route 111": { "grass": [], "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 112": { "grass": [] },
        "Fiery Path": { "grass": [] },
        "Route 113": { "grass": [] },
        "Route 114": { "grass": [], "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Meteor Falls": { "grass": [], "surf": [] },
        "Route 115": { "grass": [], "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 116": { "grass": [] },
        "Jagged Pass": { "grass": [] },
        "Mt. Chimney": { "grass": [] },
        "Route 117": { "grass": [] },
        "Route 118": { "grass": [], "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 119": { "grass": [], "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Weather Institute": { "grass": [] },
        "Route 120": { "grass": [], "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 121": { "grass": [], "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Safari Zone": { "grass": [] },
        "Route 122": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Mt. Pyre": { "grass": [], "surf": [] },
        "Route 123": { "grass": [] },
        "Route 124": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 125": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Shoal Cave": { "grass": [], "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 126": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 127": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 128": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Seafloor Cavern": { "surf": [] },
        "Route 129": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 130": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 131": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Sky Pillar": { "grass": [] },
        "Pacifidlog Town": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 132": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 133": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] },
        "Route 134": { "surf": [], "fish_old": [], "fish_good": [], "fish_super": [] }
    }
};

export default encounterData;
